### ISSUE TITLE
estimateFee crashes, when fee exceeds Number.MAX_SAFE_INTEGER

### ISSUE THREAD

**Issue by bartekryba** [seanjameshan/starknet.js#186]
estimate_fee endpoint returns data with two fields: amount and unit, e.g.:
`{"amount": 6525000005, "unit": "wei"}`
which is parsed in fetchEndpoint in such a way, that amount is of type number, not string or BN.

This creates a problem when calling Account.estimateFee. When returned amount exceeds Number.MAX_SAFE_INTEGER, BN constructor's assert fails, resulting in such error:
```
Error: Assertion failed
    at assert (bn.js:6:21)
    at BN._initNumber (bn.js:128:7)
    at BN.init [as _init] (bn.js:82:19)
    at new BN (bn.js:39:12)
    at toBN (number.js:36:12)
    at Object.estimatedFeeToMaxFee (stark.js:89:29)
```

Quick solution would be to just run toString() on amount, before passing it to estimatedFeeToMaxFee. (As estimateFee is an estimate, potential loss of precision shouldn't be a problem). But maybe it's better to handle problems like this more generically, when parsing data from fetchEndpoint?

starknet.js version: **3.10.2**

**Comment by janek26** [comment]
can you please check the branch of #187 and let me know if you still have a problem?

**Comment by bartekryba** [comment]
It worked for me, thank you!
