### ISSUE TITLE
Usage with Create React App

### ISSUE THREAD

**Issue by fracek** [seanjameshan/starknet.js#37]
I made an example using [this library with react](https://github.com/fracek/starknet-react-example), everything is working fine in development, but in production it looks like starknet.js is throwing a type error. You can [open this page](http://starknet-react-example.vercel.app/) to see the error more in detail.

To reproduce locally:

 * Clone my example repo
 * Build with `yarn run build`
 * Serve production build with `yarn run serve`

**Comment by janek26** [comment]
Hey,

please have a look here:
https://github.com/paulmillr/noble-ed25519/issues/23

it seems like the issue is in react scripts code, could you try to locate that bug in their source code? 

Have you tried with next's/parcel? :) So we'd know if it's a general thing

**Comment by janek26** [comment]
This helps:

```javascript
"browserslist": {
    "production": [
      "chrome >= 67",
      "edge >= 79",
      "firefox >= 68",
      "opera >= 54",
      "safari >= 14"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
```

in package.json

The issue is that native biting support is required atm

**Comment by fracek** [comment]
This worked like a charm (had to delete `node_modules`). Closing, thank you again.

**Comment by MorganIsBatman** [comment]
> ```js
> "browserslist": {
>     "production": [
>       "chrome >= 67",
>       "edge >= 79",
>       "firefox >= 68",
>       "opera >= 54",
>       "safari >= 14"
>     ],
>     "development": [
>       "last 1 chrome version",
>       "last 1 firefox version",
>       "last 1 safari version"
>     ]
>   }
> ```

You are a legend @janek! I was about to gear myself up to faff about with my tsconfig when I found this.  Instant solve!  Thank you sir

**Comment by maht0rz** [comment]
@janek26 your fix just saved my day, i wonder what is the actual root cause of this problem - but thanks!

**Comment by janek26** [comment]
> The issue is that native BigInt support is required atm

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt#browser_compatibility

Hopefully this will be fixed soon by StarkWare switching BigInts to hex strings in compiled contracts

**Comment by 0xs34n** [comment]
Users who build on the web should probably use `next.js` as there is an issue with the following packages:

https://github.com/0xs34n/starknet.js/issues/172

https://github.com/0xs34n/starknet.js/issues/131
