### ISSUE TITLE
replace axios by fetch

### ISSUE THREAD

**Issue by janek26** [seanjameshan/starknet.js#40]
Should we replace axios by some isomorphic fetch implementation to have less dependencies in case the used environment already has fetch available? :) It would not introduce any extra complexity as we can't use most of axis advantages anyways when handling biting json data.

Would love to hear your thoughts @seanjameshan 

I'd suggest https://github.com/lquixada/cross-fetch

**Comment by seanjameshan** [comment]
Sounds good. I'm cool with it

**Comment by seanjameshan** [comment]
As far as I understand, Axios will use the fetch implementation under the hood if it is available?

I chose Axios because it seemed like the industry standard as far as fetching goes.
