### ISSUE TITLE
Deploying contracts returns error

### ISSUE THREAD

**Issue by seanjameshan** [seanjameshan/starknet.js#46]
```
data: {
  code: 'StarknetErrorCode.SECURITY_ERROR',
  message: 'Invalid value for field prime:  
    3618502788666131106986593281521497120414687020801267626233049500247285301248. Expected: 
    3.618502788666131e+75.  
    3618502788666131213697322783095070105623107215331596699973092056135872020481.'
}
```   

Getting the following error when deploying the AMM compiled code [here](https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starknet/apps/amm_sample/amm_sample.cairo)

However, it works when you use the `starknet deploy` command

**Comment by himanshuchawla009** [comment]
You need to parse the compiled contract to convert these bignumber to strings so that they can be correctly parsed in javascript. It works perfectly in python or with commandline but doesn't work with javascript because javascript converts these big numbers in to floating points.

**Comment by janek26** [comment]
please use 

```javascript
import { json } from "starknet"
const parsedContract = json.parse(compiledContractAsString)
```

in these cases
