### ISSUE TITLE
verify function doesn't work correctly, plz also add a test case for that.

### ISSUE THREAD

**Issue by himanshuchawla009** [seanjameshan/starknet.js#50]
- Sign a message with sign function and try to verify it, verification function will return false always even if hash and signature passed is correct.

**Comment by seanjameshan** [comment]
How are you calling the sign function?

**Comment by himanshuchawla009** [comment]
Here is code snippet which can reproduce the issue:-

```
     import {  pedersen, getKeyPair, sign } from "starknet";
     
      const signingKeyPair = getKeyPair(ethereumPrivKey);
     const somePedersenMsgHash =  pedersen([
      "58f580910a6ca59b28927c08fe6c43e2e303ca384badc365795fc645d479d45",
      "78734f65a067be9bdb39de18434d71e79f7b6466a4b66bbd979ab9e7515fe0b",
    ]);
      const signature = sign(signingKeyPair, somePedersenMsgHash);

     // in real use case i will keypair derived from public key while verification
     const isVerified = verify(signingKeyPair, somePedersenMsgHash, signature );

```

isVerified is returning false, it should return true.

I investigated this issue, i believe issue is here:
https://github.com/seanjameshan/starknet.js/blob/f2b26febaf52a1aebe88159480800ee2899ff1d5/src/ellipticalCurve.ts#L93

fixMessage function is not being called on msgHash in verification function as it is being called on sign function, so verify is not working @seanjameshan

**Comment by seanjameshan** [comment]
Thanks for the fix!
