### ISSUE TITLE
move `getSelectorFromName()` to `starknet`from `utils/starknet`

### ISSUE THREAD

**Issue by seanjameshan** [seanjameshan/starknet.js#56]
`getSelectorFromName()` is used very frequently with dapps. Every time I make a smart contract call I would have to import like the following: 

```javascript
const {
  starknet: { getSelectorFromName },
} = utils;
```

Would prefer this import instead:

```javascript
import { getSelectorFromName, addTransaction } from "starknet";
```

I am not using Provider / Signer at the moment so this could possibly be outdated

**Comment by janek26** [comment]
use signer and provider and this should be solved (together with the contract class)

You should use them anyways to be compatible with argent X ;)
