### ISSUE TITLE
Signing transactions

### ISSUE THREAD

**Issue by 0xs34n** [seanjameshan/starknet.js#7]
@janek26 Feel free to add more context to this use case.

https://github.com/authereum/starkware-monorepo

**Comment by seanjameshan** [comment]
Interesting notes from @martriay of @openzeppelin 

**Python implementation**

https://github.com/OpenZeppelin/cairo-contracts/blob/main/test/Account.py

https://github.com/OpenZeppelin/cairo-contracts/blob/main/test/utils/Signer.py

**Smart contract account abstraction:**

https://github.com/OpenZeppelin/cairo-contracts/blob/main/contracts/Account.cairo

https://github.com/OpenZeppelin/cairo-contracts/blob/main/contracts/IAccount.cairo
