### ISSUE TITLE
Typo in testnet name

### ISSUE THREAD

**Issue by milancermak** [seanjameshan/starknet.js#83]
The [Görli](https://ethereum.org/en/developers/docs/networks/#goerli) testnet is spelled `goerli` not [`georli`](https://github.com/seanjameshan/starknet.js/blob/100e69db2ee764895b8bd845f5f5c20317286450/src/provider/default.ts#L21).

I can send a PR to fix it, just nott sure how you want to handle it since this might be a breaking change.

**Comment by janek26** [comment]
https://github.com/seanjameshan/starknet.js/pull/97
