### ISSUE TITLE
deployContract deploys a faulty contract

### ISSUE THREAD

**Issue by GeraldHost** [seanjameshan/starknet.js#84]
I was receiving the error `AssertionError: normalize_address() cannot be used with the current constants` when calling a contract I deployed with `provider.deployContract`. After investigating the issue with Tom (starknet) on discord he has suggested that it is possibly something to do with the way starknet JS is handling ints from the `compile_contract.json` file that is passed in as the first argument to `deployContract`

This is the code I am using to deploy my contract:

```js
const calldata = compileCalldata({
    name: nameFelt,
    symbol: symbolFelt,
    owner: account,
});

const resp = await provider.deployContract(compiledERC721, calldata);
```

This is the JSON file:

https://github.com/GeraldHost/fractor/blob/master/packages/fractor-web/src/constants/contracts/erc721.json

And here is a script that shows the error when calling a contract deployed with the starknet CLI that works and then that same contract deployed with starknet.js that doesn't work:

https://github.com/GeraldHost/fractor/blob/master/packages/fractor-contracts/scripts/starknet_js_test.js

Appreciate the time and help

**Comment by janek26** [comment]
hey @GeraldHost 

can you add the code snippet where you deployed the contract ?
Maybe something went wrong while deploying, even tho it seems unlikely to me

**Comment by GeraldHost** [comment]
@janek26 sure this is the fuller code:

```js
 const nameFelt = strToFelt(name);
 const symbolFelt = strToFelt(symbol);

 const calldata = compileCalldata({
    name: nameFelt,
    symbol: symbolFelt,
    owner: account,
 });

 const resp = await provider.deployContract(compiledERC721, calldata);
```

`account` is a hex string coming from `window.starknet` and `strToFelt` returns a number string i.e `"123"`

I think it must be deployment related because if I deploy the contract with the CLI all the UI code works fine it's just if this above code is use to deploy I start getting those errors.

**Comment by janek26** [comment]
@GeraldHost I See you importing compiled contracts using language features, which will apply `JSON.parse` on them. Please try again with importing the json as text (no parsing) and parse as described here:

https://github.com/seanjameshan/starknet.js/issues/46#issuecomment-966982725

to retain the biting fields when deploying

**Comment by GeraldHost** [comment]
@janek26 you my friend are a legend! Thank you that was exactly the issue! 🤘
